#2.13
import turtle
def head():
    turtle.speed(1)
    turtle.color('brown')
    turtle.begin_fill()
    turtle.circle(100)
    turtle.end_fill()
def eyes():
    turtle.color('red')
    turtle.begin_fill()
    turtle.up()
    turtle.goto(35, 130)
    turtle.down()
    turtle.circle(10)
    turtle.end_fill()

    turtle.begin_fill()
    turtle.up()
    turtle.goto(-35, 130)
    turtle.down()
    turtle.circle(10)
    turtle.end_fill()
def mouth():
    turtle.width(5)
    turtle.color('red')
    turtle.up()
    turtle.goto(30, 50)
    turtle.left(90)
    turtle.down()
    turtle.circle(30, -180)
def nose():
    turtle.width(10)
    turtle.color('orange')
    turtle.up()
    turtle.goto(0, 110)
    turtle.left(90)
    turtle.down()
    turtle.left(90)
    turtle.backward(45)
head()
eyes()
mouth()
nose()